SistemaWebMisRecetas/Models/Receta.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using SistemaWebMisRecetas.Validations;

namespace SistemaWebMisRecetas.Models
{
    public class Receta
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Campo obligatorio.")]
        [Column(TypeName = "varchar(50)")]
        [StringLength(50)] 
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Campo obligatorio.")]
        [CategoriaAttribute]
        [Column(TypeName = "varchar(50)")]
        [StringLength(50)] 
        public string Categoria { get; set; }

        [Required(ErrorMessage = "Campo obligatorio.")]
        [DataType(DataType.MultilineText)]
        [Column(TypeName = "varchar(200)")]
        [StringLength(200)] 
        public string Ingredientes { get; set; }

        [Required(ErrorMessage = "Campo obligatorio.")]
        [DataType(DataType.MultilineText)]
        [Column(TypeName = "varchar(200)")]
        [StringLength(200)] 
        public string Instrucciones { get; set; }

        [Required(ErrorMessage = "Campo obligatorio.")]
        [Column(TypeName = "varchar(50)")]
        [StringLength(50)] 
        public string NombreAutor { get; set; }

        [Required(ErrorMessage = "Campo obligatorio.")]
        [Column(TypeName = "varchar(50)")]
        [StringLength(50)] 
        public string ApellidoAutor { get; set; }

        [Required(ErrorMessage = "Campo obligatorio.")]
        [EdadAttribute]
        public int EdadAutor { get; set; }

        [Required(ErrorMessage = "Campo obligatorio.")]
        [Column(TypeName = "varchar(50)")]
        [StringLength(50)] 
        public string EmailAutor { get; set; }



    }
}

SistemaWebMisRecetas/Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace SistemaWebMisRecetas.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Nombre = "Bienvenido Mis Recetas";
            return View();
        }
    }
}

SistemaWebMisRecetas/Controllers/RecetaController.cs
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SistemaWebMisRecetas.Data;
using SistemaWebMisRecetas.Models;

namespace SistemaWebMisRecetas.Controllers
{
    public class RecetaController : Controller
    {

        //Inyección de dependencias.

        private readonly RecetasContext context;

        public RecetaController(RecetasContext context)
        {
            this.context = context;
        }

        //GET Receta/index
        [HttpGet]
        public IActionResult Index()
        {
            var recetas = context.Recetas.ToList();
            return View(recetas);
        }


        //Get: Receta/create
        [HttpGet]
        public ActionResult Create()
        {
            Receta receta = new Receta();

            return View("Create", receta);
        }

        //post: Receta/create
        [HttpPost]
        public ActionResult Create(Receta receta)
        {
            if (ModelState.IsValid)
            {
                context.Recetas.Add(receta);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(receta);
        }

        //GET Receta/Details/4
        [HttpGet]
        public ActionResult Details(int id)
        {
            Receta receta = context.Recetas.Find(id);
            if (receta == null)
            {
                return NotFound();
            }
            else
            {
                return View("Details", receta);
            }

        }

        //GET Receta/ByNombreAutor/nombreAutor
        [HttpGet("{nombreAutor}")]
        public ActionResult<IEnumerable<Receta>> ByNombreAutor(string NombreAutor)
        {
            var receta = (from a in context.Recetas
                            where a.NombreAutor == NombreAutor
                            select a).ToList();
            return View("ByNombreAutor", receta);

        }


        //GET Receta/ByApellidoAutor/ApellidoAutor
        [HttpGet("/apellido/{apellidoAutor}")]
        public ActionResult<IEnumerable<Receta>> ByApellidoAutor(string ApellidoAutor)
        {
            var receta = (from a in context.Recetas
                          where a.ApellidoAutor == ApellidoAutor
                          select a).ToList();
            return View("ByApellidoAutor", receta);

        }

    }
}

SistemaWebMisRecetas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index Home";
}

@Html.ActionLink("Ir a Mis Recetas", "Index", "Receta")

@section SideBar{


                <div class="sidebar1">
                <h4>Bienvenidos a Mis Recetas</h4>
                <img src="~/fotos/imagen01.png" alt="Imágen no encontrada"/>
                <img src="~/fotos/imagen02.jpg" alt="Imágen no encontrada"/>
                <img src="~/fotos/imagen03.jpg" alt="Imágen no encontrada"/>
            </div>

        }
        <div>
            <p>
                El desayuno es la primera comida que se consume en el día. El nombre deriva del hecho de que uno no come mientras duerme, por lo que al levantarse se encuentra en ayunas, rompiéndose ese ayuno al tomar esta comida (des-ayuno).
            </p>
            <p>
                El desayuno es la comida fundamental del día, ya que consumirlo o no, nos afecta de forma notable a corto y a largo plazo.[cita requerida]

                Se ha demostrado que los niños que no desayunan o que solo toman un vaso de leche, rinden menos en el colegio que los que ingieren un desayuno adecuado.1​
            </p>
            <p>
                En Estados Unidos de América el desayuno completo consiste en panceta, huevos, hash browns y tostada. A menudo se le denomina country breakfast (‘desayuno campestre’) en muchas zonas del Medio Oeste. Los términos fry y full breakfast no suelen usarse en Norteamérica, si bien algunos hoteles pueden distinguir entre un continental breakfast ligero y un desayuno caliente.
            </p>
        </div>

SistemaWebMisRecetas/Views/Receta/ByApellidoAutor.cshtml
@model IEnumerable<SistemaWebMisRecetas.Models.Receta>
@{
    ViewData["Title"] = "Lista de recetas";
}
@Html.ActionLink("Volver", "Index", "Receta")


@section SideBar {
    @Html.ActionLink("Nueva Receta", "Create", "Receta")
}

    <table>
        <tr>
            <th>@Html.DisplayNameFor(m=> m.Nombre)</th>
            <th>@Html.DisplayNameFor(m=> m.Categoria)</th>
            <th>@Html.DisplayNameFor(m=> m.NombreAutor)</th>
            <th>@Html.DisplayNameFor(m=> m.ApellidoAutor)</th>
        </tr>

    @foreach (var receta in Model)
    {
                        <tr>
                            <td>
                @Html.DisplayFor(m=> receta.Nombre)
                            </td>
                            <td>
                @Html.DisplayFor(m=> receta.Categoria)
                            </td>
                            <td>
                @Html.DisplayFor(m=> receta.NombreAutor)
                            </td>
                            <td>
                @Html.DisplayFor(m=> receta.ApellidoAutor)
                            </td>
                            <td>

                            </td>

                            <td>
                            </td>

                        </tr>
    }
    </table>

SistemaWebMisRecetas/Views/Receta/ByNombreAutor.cshtml
@model IEnumerable<SistemaWebMisRecetas.Models.Receta>
@{
    ViewData["Title"] = "Lista de recetas";
}
@Html.ActionLink("Volver", "Index", "Receta")


@section SideBar {
    @Html.ActionLink("Nueva Receta", "Create", "Receta")
}

    <table>
        <tr>
            <th>@Html.DisplayNameFor(m=> m.Nombre)</th>
            <th>@Html.DisplayNameFor(m=> m.Categoria)</th>
            <th>@Html.DisplayNameFor(m=> m.NombreAutor)</th>
            <th>@Html.DisplayNameFor(m=> m.ApellidoAutor)</th>
        </tr>

    @foreach (var receta in Model)
    {
                    <tr>
                        <td>
                @Html.DisplayFor(m=> receta.Nombre)
                        </td>
                        <td>
                @Html.DisplayFor(m=> receta.Categoria)
                        </td>
                        <td>
                @Html.DisplayFor(m=> receta.NombreAutor)
                        </td>
                        <td>
                @Html.DisplayFor(m=> receta.ApellidoAutor)
                        </td>
                        <td>

                        </td>

                        <td>
                        </td>

                    </tr>
    }
    </table>

SistemaWebMisRecetas/Views/Receta/Create.cshtml
@model SistemaWebMisRecetas.Models.Receta;


@{
    ViewData["Title"] = "Create";
}

    <h1>Crear Receta</h1>
@using (Html.BeginForm("Create", "Receta", FormMethod.Post))
{
                <p> 
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre)
        @Html.ValidationMessageFor(model => model.Nombre)
                </p>

                <p> 
        @Html.LabelFor(model => model.Categoria)
        @Html.TextBoxFor(model => model.Categoria)
        @Html.ValidationMessageFor(model => model.Categoria)
                 </p>
                    <p> 
        @Html.LabelFor(model => model.Ingredientes)
        @Html.TextBoxFor(model => model.Ingredientes)
        @Html.ValidationMessageFor(model => model.Ingredientes)
                     </p>
                    <p> 
        @Html.LabelFor(model => model.Instrucciones)
        @Html.TextBoxFor(model => model.Instrucciones)
        @Html.ValidationMessageFor(model => model.Instrucciones)
                     </p>

                 <p> 
        @Html.LabelFor(model => model.NombreAutor)
        @Html.TextBoxFor(model => model.NombreAutor)
        @Html.ValidationMessageFor(model => model.NombreAutor)
                 </p>
                 <p>
        @Html.LabelFor(model => model.ApellidoAutor)
        @Html.TextBoxFor(model => model.ApellidoAutor)
        @Html.ValidationMessageFor(model => model.ApellidoAutor)
                 </p>
                     <p>
        @Html.LabelFor(model => model.EdadAutor)
        @Html.TextBoxFor(model => model.EdadAutor)
        @Html.ValidationMessageFor(model => model.EdadAutor)
                     </p>
                     <p>
        @Html.LabelFor(model => model.EmailAutor)
        @Html.TextBoxFor(model => model.EmailAutor)
        @Html.ValidationMessageFor(model => model.EmailAutor)
                     </p>

                 <input type="submit" action="Create"/>

    @Html.ActionLink("Volver a Index", "Index", "Receta")

}

SistemaWebMisRecetas/Views/Receta/Details.cshtml
@model SistemaWebMisRecetas.Models.Receta;

@{
    ViewData["Title"] = "Detalle";
}
@section SideBar {
    @Html.ActionLink("Nueva Receta", "Create", "Receta")
}
    <h2> Ver Detalles</h2>
@Html.ActionLink("Volver al index", "Index", "Receta")
    <p>
    @Html.DisplayNameFor(model => model.Nombre): 
    @Html.DisplayFor(model => model.Nombre)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.Categoria): 
    @Html.DisplayFor(model => model.Categoria)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.Ingredientes): 
    @Html.DisplayFor(model => model.Ingredientes)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.Instrucciones): 
    @Html.DisplayFor(model => model.Instrucciones)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.NombreAutor): 
    @Html.DisplayFor(model => model.NombreAutor)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.ApellidoAutor): 
    @Html.DisplayFor(model => model.ApellidoAutor)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.EdadAutor): 
    @Html.DisplayFor(model => model.EdadAutor)
    </p>
    <p>
    @Html.DisplayNameFor(model => model.EmailAutor): 
    @Html.DisplayFor(model => model.EmailAutor)
    </p>

SistemaWebMisRecetas/Views/Receta/Index.cshtml
@model IEnumerable<SistemaWebMisRecetas.Models.Receta>

@{
    ViewData["Title"] = "Index";
}
@section SideBar{
    @Html.ActionLink("Nuevo", "Create", "Receta")
}


    <Table>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nombre)</th>
            <th>@Html.DisplayNameFor(model => model.Categoria)</th>
            <th>@Html.DisplayNameFor(model => model.NombreAutor)</th>
            <th>@Html.DisplayNameFor(model => model.ApellidoAutor)</th>
            <th></th>

        </tr>

    @foreach (var item in Model)
    {
                <tr>
                    <td>
                @*@Html.DisplayFor(modelItem => item.Nombre)*@
                @Html.ActionLink(item.Nombre, "Details", "Receta", new{id=item.Id})

                    </td>

                    <td>
                @Html.DisplayFor(modelItem => item.Categoria)
                    </td>

                    <td>
                @*@Html.DisplayFor(modelItem => item.NombreAutor)*@
                @Html.ActionLink(item.NombreAutor, "ByNombreAutor", "Receta",new{nombreAutor=item.NombreAutor})
                    </td>
                                            <td>
             @*   @Html.DisplayFor(modelItem => item.ApellidoAutor)*@
                @Html.ActionLink(item.ApellidoAutor, "ByApellidoAutor", "Receta",new{apellidoAutor=item.ApellidoAutor})
                        </td>
                    <td>

                    </td>
                </tr>
    }

    </Table>

SistemaWebMisRecetas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/site.css" rel="stylesheet" type="text/css"/>
</head>
@*<body>

    <div id="header">
        <h1>Mis Recetas</h1>
    </div>
        <div id="menu">
        @Html.ActionLink("Inicio","Index","Home")
        @Html.ActionLink("Receta","Index","Receta")
    </div>
    <div id="sidebar">
        @if (IsSectionDefined("SideBar"))
        {
            @RenderSection("SideBar")
        }
        else
        {
         <h2>Mis Recetas. </h2>
        }
    </div>


    <div class="main">

        <div id="content">
            @RenderBody()
        </div>
    </div>

    <div id="footer">
        <p>MisRecetas@web.com</p>
    </div>
</body>
</html>*@

<body>
    <div class="principal">
        <div class="navbar">
            <div class="navinterno">
                <h1> Mis Recetas</h1>

            </div>
            <div class="navinterno">

                @Html.ActionLink("Home", "Index", "Home")
                @Html.ActionLink("Ir a las recetas","Index","Receta")
                @Html.ActionLink("Create", "Create", "Receta")


            </div>
        </div>

        <div class="bodyid">
          }
            <div class="renderbody">
                @RenderBody()

            </div>


            <div class="sidebarR">
                @if (IsSectionDefined("SideBar"))
                {
                    @RenderSection("SideBar")
                }
                else
                {
             <h2>Mis Recetas. </h2>
                }
            </div>

        </div>
        <div class="footer">

            <h2>info@misrecetas.com</h2>

        </div>

    </div>
</body>
</html>